/** Alphabets Worksheets gallery — 16 pages × 3 cards */

export const ALPHABET_WORKSHEET_CARDS = [
  { id: "alpha-ws-p1-find-mango", locked: false },
  { id: "alpha-ws-p1-write-correct-sun", locked: false },
  { id: "alpha-ws-p1-write-last-duck", locked: false },
  { id: "alpha-ws-p2-write-correct", locked: true },
  { id: "alpha-ws-p2-write-last", locked: true },
  { id: "alpha-ws-p2-find-shells", locked: true },
  { id: "alpha-ws-p3-trace-pig", locked: true },
  { id: "alpha-ws-p3-write-correct-train", locked: true },
  { id: "alpha-ws-p3-sequence-shirts", locked: true },
  { id: "alpha-ws-p4-match-scramble", locked: true },
  { id: "alpha-ws-p4-trace-quail-hat", locked: true },
  { id: "alpha-ws-p4-path-rabbit", locked: true },
  { id: "alpha-ws-p5-write-first-crab", locked: true },
  { id: "alpha-ws-p5-trace-strawberry", locked: true },
  { id: "alpha-ws-p5-write-correct-cup", locked: true },
  { id: "alpha-ws-p6-circle-m", locked: true },
  { id: "alpha-ws-p6-trace-elephant", locked: true },
  { id: "alpha-ws-p6-write-last-leaf", locked: true },
  { id: "alpha-ws-p7-complete-seq1", locked: true },
  { id: "alpha-ws-p7-odd-one-out1", locked: true },
  { id: "alpha-ws-p7-complete-seq2", locked: true },
  { id: "alpha-ws-p8-match-uah", locked: true },
  { id: "alpha-ws-p8-match-nyg", locked: true },
  { id: "alpha-ws-p8-match-upper-lower", locked: true },
  { id: "alpha-ws-p9-circle-p", locked: true },
  { id: "alpha-ws-p9-match-orv", locked: true },
  { id: "alpha-ws-p9-circle-k", locked: true },
  { id: "alpha-ws-p10-path-orange", locked: true },
  { id: "alpha-ws-p10-path-star", locked: true },
  { id: "alpha-ws-p10-path-cupcake", locked: true },
  { id: "alpha-ws-p11-odd-one-out2", locked: true },
  { id: "alpha-ws-p11-match-asl", locked: true },
  { id: "alpha-ws-p11-complete-seq3", locked: true },
  { id: "alpha-ws-p12-path-yak", locked: true },
  { id: "alpha-ws-p12-path-nest", locked: true },
  { id: "alpha-ws-p12-path-hat", locked: true },
  { id: "alpha-ws-p13-complete-abc", locked: true },
  { id: "alpha-ws-p13-circle-a", locked: true },
  { id: "alpha-ws-p13-odd-one-out3", locked: true },
  { id: "alpha-ws-p14-match-gbm", locked: true },
  { id: "alpha-ws-p14-match-jei", locked: true },
  { id: "alpha-ws-p14-path-pig", locked: true },
  { id: "alpha-ws-p15-match-ugp", locked: true },
  { id: "alpha-ws-p15-match-dnq", locked: true },
  { id: "alpha-ws-p15-odd-one-out4", locked: true },
  { id: "alpha-ws-p16-match-bwj", locked: true },
  { id: "alpha-ws-p16-match-bze", locked: true },
  { id: "alpha-ws-p16-match-xfk", locked: true },
] as const;

export const ALPHABET_WORKSHEET_CARD_IDS = ALPHABET_WORKSHEET_CARDS.map((c) => c.id);

export type AlphabetWorksheetCardId = (typeof ALPHABET_WORKSHEET_CARD_IDS)[number];
